apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vote-app-chart.fullname" . }}-db-secret
type: Opaque
data:
  # Use 'echo -n "yourpassword" | base64' to get these values
  db-password: {{ .Values.db.password | b64enc | quote }} # use your own password
  django-secret-key: {{ .Values.db.password | b64enc | quote }} # use your own secret key from settings.py

