apiVersion: v1
kind: Service
metadata:
  name: {{ include "vote-app-chart.fullname" . }}-db-service
spec:
  selector:
    app: {{ include "vote-app-chart.fullname" . }}-postgres
  ports:
  - port: 5432
  clusterIP: None # This makes it a "Headless" service

