# pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "vote-app-chart.fullname" . }}-pv
spec:
  capacity:
    storage: {{ .Values.persistentVolume.capacity }}
  accessModes:
    - {{ .Values.persistentVolume.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistentVolume.storageClassName }}
  hostPath:
    path: {{ .Values.persistentVolume.hostpath.path }}

